# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

from __future__ import annotations

import enum
import uuid
from collections import deque
from dataclasses import dataclass

from vllm.logger import init_logger

from vllm_omni.diffusion.data import DiffusionOutput, OmniDiffusionConfig, StepDiffusionOutput
from vllm_omni.diffusion.request import OmniDiffusionRequest

logger = init_logger(__name__)


class DiffusionRequestStatus(enum.IntEnum):
    """Request status tracked by diffusion scheduler."""

    WAITING = enum.auto()
    RUNNING = enum.auto()
    PREEMPTED = enum.auto()

    # if any status is after FINISHED_COMPLETED, it is considered finished
    FINISHED_COMPLETED = enum.auto()
    FINISHED_ABORTED = enum.auto()
    FINISHED_ERROR = enum.auto()

    @staticmethod
    def is_finished(status: DiffusionRequestStatus) -> bool:
        return status >= DiffusionRequestStatus.FINISHED_COMPLETED


@dataclass
class DiffusionRequestState:
    """Scheduler-owned state for one queued OmniDiffusionRequest."""

    req_id: str  # unique request ID generated by scheduler
    req: OmniDiffusionRequest
    current_infer_step: int = 0
    status: DiffusionRequestStatus = DiffusionRequestStatus.WAITING
    error: str | None = None


@dataclass
class DiffusionSchedulerOutput:
    """Output of a single scheduling cycle."""

    step_id: int
    req_states: list[DiffusionRequestState]
    finished_req_ids: set[str]
    num_running_reqs: int
    num_waiting_reqs: int


class Scheduler:
    """Diffusion scheduler with vLLM-style waiting/running queues.

    NOTE: Currently, each OmniDiffusionRequest is already pre-batched upstream.
    Scheduler only handles request-level state transitions and never merges
    multiple requests into a new batch.
    """

    def __init__(self) -> None:
        self.od_config: OmniDiffusionConfig | None = None
        self._request_states: dict[str, DiffusionRequestState] = {}
        self._step_id: int = 0

        self._waiting: deque[str] = deque()
        self._running: list[str] = []
        self._finished_req_ids: set[str] = set()

    def initialize(self, od_config: OmniDiffusionConfig) -> None:
        self.od_config = od_config
        self._request_states.clear()
        self._step_id = 0

        self._waiting.clear()
        self._running.clear()
        self._finished_req_ids.clear()

    def add_request(self, request: OmniDiffusionRequest) -> str:
        req_id = self._make_req_id(request)
        state = DiffusionRequestState(req_id=req_id, req=request)
        self._request_states[req_id] = state
        self._waiting.append(req_id)
        logger.debug("Scheduler add_request: %s (waiting=%d)", req_id, len(self._waiting))
        return req_id

    def schedule(self) -> DiffusionSchedulerOutput:
        MAX_CONCURRENT_REQS = self.od_config.max_num_seqs if self.od_config else 1
        # Single-request scheduling: do not build multiple request batches.
        while len(self._running) < MAX_CONCURRENT_REQS and self._waiting:
            req_id = self._waiting.popleft()
            state = self._request_states.get(req_id)
            if state is not None:  # why we need this?
                state.status = DiffusionRequestStatus.RUNNING
                self._running.append(req_id)

        running_states: list[DiffusionRequestState] = []
        for req_id in self._running:
            state = self._request_states.get(req_id)
            if state is not None:
                running_states.append(state)

        scheduler_output = DiffusionSchedulerOutput(
            step_id=self._step_id,
            req_states=running_states,
            finished_req_ids=set(self._finished_req_ids),
            num_running_reqs=len(self._running),
            num_waiting_reqs=len(self._waiting),
        )

        # update after schedule
        self._step_id += 1
        self._finished_req_ids.clear()
        return scheduler_output

    def update_from_output(
        self, sched_output: DiffusionSchedulerOutput, output: DiffusionOutput | list[StepDiffusionOutput]
    ) -> tuple[set[str], list[StepDiffusionOutput]]:
        scheduled_req_ids = {state.req_id for state in sched_output.req_states}
        if not scheduled_req_ids:
            return set(), []

        completed_req_ids: set[str] = set()
        completed_reqs: list[StepDiffusionOutput] = []
        if isinstance(output, DiffusionOutput): # need refine
            if output.error:
                for req_id in scheduled_req_ids:
                    state = self._request_states.get(req_id)
                    if state is None:
                        continue
                    state.status = DiffusionRequestStatus.FINISHED_ERROR
                    state.error = output.error
                    completed_req_ids.add(req_id)
            else:
                for req_id in scheduled_req_ids:
                    state = self._request_states.get(req_id)
                    if state is None:
                        continue
                    state.status = DiffusionRequestStatus.FINISHED_COMPLETED
                    state.error = None
                    completed_req_ids.add(req_id)
        elif isinstance(output, list):
            for out in output:
                if out.error:
                    for req_id in scheduled_req_ids:
                        state = self._request_states.get(req_id)
                        if state is None:
                            continue
                        state.status = DiffusionRequestStatus.FINISHED_ERROR
                        state.error = out.error
                        completed_req_ids.add(req_id)
                elif not out.stimesteps: # finished, not timesteps
                    if out.req_id in scheduled_req_ids:
                        completed_reqs.append(out)
                        state = self._request_states.get(out.req_id)
                        if state is None:
                            continue
                        state.status = DiffusionRequestStatus.FINISHED_COMPLETED
                        state.error = None
                        completed_req_ids.add(out.req_id)

        if completed_req_ids:
            self._running = [
                req_id for req_id in self._running if req_id not in completed_req_ids
            ]  # maybe more Concise
            for req_id in completed_req_ids:
                try:
                    self._waiting.remove(req_id) # why we need remove req from waiting?
                except ValueError:
                    pass
            self._finished_req_ids |= completed_req_ids

        return completed_req_ids, completed_reqs

    def abort_request(self, req_id: str) -> bool:
        if req_id not in self._request_states:
            return False
        self.finish_request(req_id, DiffusionRequestStatus.FINISHED_ABORTED)
        self._finished_req_ids.add(req_id)
        return True

    def has_requests(self) -> bool:
        return bool(self._waiting or self._running)

    def get_request_state(self, req_id: str) -> DiffusionRequestState | None:
        return self._request_states.get(req_id)

    def pop_request_state(self, req_id: str | list[str]) -> DiffusionRequestState | list[DiffusionRequestState] | None:
        return self._request_states.pop(req_id, None)

    def preempt_request(self, req_id: str) -> bool:
        if req_id not in self._request_states:
            return False
        if req_id in self._running:
            self._running.remove(req_id)
            self._waiting.appendleft(req_id)
            self._request_states[req_id].status = DiffusionRequestStatus.PREEMPTED
            return True
        return False

    def finish_request(self, req_id: str, status: DiffusionRequestStatus) -> None:
        assert DiffusionRequestStatus.is_finished(status)
        state = self._request_states.get(req_id)
        if state is None:
            return

        state.status = status
        if req_id in self._running:
            self._running.remove(req_id)
        try:
            self._waiting.remove(req_id)
        except ValueError:
            pass

    def close(self) -> None:
        self._request_states.clear()
        self._waiting.clear()
        self._running.clear()
        self._finished_req_ids.clear()

    def _make_req_id(self, request: OmniDiffusionRequest) -> str:
        """
        Generate a unique request ID for the given request.
        If the request already has request IDs, use the first one as the base.

        NOTE: OmniDiffusionRequest already contain multiple prompts/outputs
        as a pre-batched request object.
        """
        if request.request_ids:
            base = request.request_ids[0]
        else:
            base = f"req_{uuid.uuid4().hex[:8]}"

        req_id = base
        suffix = 1
        while req_id in self._request_states:
            req_id = f"{base}#{suffix}"
            suffix += 1
        return req_id
