# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

from __future__ import annotations

import enum
import uuid
from collections import deque
from dataclasses import dataclass

from vllm.logger import init_logger

from vllm_omni.diffusion.data import DiffusionOutput, OmniDiffusionConfig
from vllm_omni.diffusion.request import OmniDiffusionRequest

logger = init_logger(__name__)


class DiffusionRequestStatus(enum.IntEnum):
    """Request status tracked by diffusion scheduler."""

    WAITING = enum.auto()
    RUNNING = enum.auto()
    PREEMPTED = enum.auto()

    # if any status is after FINISHED_COMPLETED, it is considered finished
    FINISHED_COMPLETED = enum.auto()
    FINISHED_ABORTED = enum.auto()
    FINISHED_ERROR = enum.auto()

    @staticmethod
    def is_finished(status: DiffusionRequestStatus) -> bool:
        return status >= DiffusionRequestStatus.FINISHED_COMPLETED


@dataclass
class DiffusionRequestState:
    """Scheduler-owned state for one queued OmniDiffusionRequest."""

    sched_req_id: str  # unique scheduler request ID generated by scheduler
    req: OmniDiffusionRequest
    status: DiffusionRequestStatus = DiffusionRequestStatus.WAITING
    error: str | None = None


@dataclass
class DiffusionSchedulerOutput:
    """Output of a single scheduling cycle."""

    step_id: int
    req_states: list[DiffusionRequestState]
    finished_req_ids: set[str]
    num_running_reqs: int
    num_waiting_reqs: int


class Scheduler:
    """Diffusion scheduler with vLLM-style waiting/running queues.

    NOTE: Currently, each OmniDiffusionRequest is already pre-batched upstream.
    Scheduler only handles request-level state transitions and never merges
    multiple requests into a new batch.
    """

    def __init__(self) -> None:
        self.od_config: OmniDiffusionConfig | None = None
        self._request_states: dict[str, DiffusionRequestState] = {}
        self._step_id: int = 0

        self._waiting: deque[str] = deque()
        self._running: list[str] = []
        self._finished_req_ids: set[str] = set()

    def initialize(self, od_config: OmniDiffusionConfig) -> None:
        self.od_config = od_config
        self._request_states.clear()
        self._step_id = 0

        self._waiting.clear()
        self._running.clear()
        self._finished_req_ids.clear()

    def add_request(self, request: OmniDiffusionRequest) -> str:
        sched_req_id = self._make_sched_req_id(request)
        state = DiffusionRequestState(sched_req_id=sched_req_id, req=request)
        self._request_states[sched_req_id] = state
        self._waiting.append(sched_req_id)
        logger.debug(
            "Scheduler add_request: %s (waiting=%d)",
            sched_req_id,
            len(self._waiting),
        )
        return sched_req_id

    def schedule(self) -> DiffusionSchedulerOutput:
        # Single-request scheduling: do not build multiple request batches.
        if not self._running and self._waiting:
            sched_req_id = self._waiting.popleft()
            state = self._request_states.get(sched_req_id)
            if state is not None:
                state.status = DiffusionRequestStatus.RUNNING
                self._running.append(sched_req_id)

        running_states: list[DiffusionRequestState] = []
        for sched_req_id in self._running:
            state = self._request_states.get(sched_req_id)
            if state is not None:
                running_states.append(state)

        scheduler_output = DiffusionSchedulerOutput(
            step_id=self._step_id,
            req_states=running_states,
            finished_req_ids=set(self._finished_req_ids),
            num_running_reqs=len(self._running),
            num_waiting_reqs=len(self._waiting),
        )

        # update after schedule
        self._step_id += 1
        self._finished_req_ids.clear()
        return scheduler_output

    def update_from_output(
        self,
        sched_output: DiffusionSchedulerOutput,
        output: DiffusionOutput,
    ) -> set[str]:
        scheduled_sched_req_ids = {state.sched_req_id for state in sched_output.req_states}
        if not scheduled_sched_req_ids:
            return set()

        completed_sched_req_ids: set[str] = set()
        if output.error:
            for sched_req_id in scheduled_sched_req_ids:
                state = self._request_states.get(sched_req_id)
                if state is None:
                    continue
                state.status = DiffusionRequestStatus.FINISHED_ERROR
                state.error = output.error
                completed_sched_req_ids.add(sched_req_id)
        else:
            for sched_req_id in scheduled_sched_req_ids:
                state = self._request_states.get(sched_req_id)
                if state is None:
                    continue
                state.status = DiffusionRequestStatus.FINISHED_COMPLETED
                state.error = None
                completed_sched_req_ids.add(sched_req_id)

        if completed_sched_req_ids:
            self._running = [
                sched_req_id for sched_req_id in self._running if sched_req_id not in completed_sched_req_ids
            ]
            for sched_req_id in completed_sched_req_ids:
                try:
                    self._waiting.remove(sched_req_id)
                except ValueError:
                    pass
            self._finished_req_ids |= completed_sched_req_ids

        return completed_sched_req_ids

    def abort_request(self, sched_req_id: str) -> bool:
        if sched_req_id not in self._request_states:
            return False
        self.finish_request(sched_req_id, DiffusionRequestStatus.FINISHED_ABORTED)
        self._finished_req_ids.add(sched_req_id)
        return True

    def has_requests(self) -> bool:
        return bool(self._waiting or self._running)

    def get_request_state(
        self,
        sched_req_id: str,
    ) -> DiffusionRequestState | None:
        return self._request_states.get(sched_req_id)

    def pop_request_state(
        self,
        sched_req_id: str,
    ) -> DiffusionRequestState | None:
        return self._request_states.pop(sched_req_id, None)

    def preempt_request(self, sched_req_id: str) -> bool:
        if sched_req_id not in self._request_states:
            return False
        if sched_req_id in self._running:
            self._running.remove(sched_req_id)
            self._waiting.appendleft(sched_req_id)
            self._request_states[sched_req_id].status = DiffusionRequestStatus.PREEMPTED
            return True
        return False

    def finish_request(
        self,
        sched_req_id: str,
        status: DiffusionRequestStatus,
    ) -> None:
        assert DiffusionRequestStatus.is_finished(status)
        state = self._request_states.get(sched_req_id)
        if state is None:
            return

        state.status = status
        if sched_req_id in self._running:
            self._running.remove(sched_req_id)
        try:
            self._waiting.remove(sched_req_id)
        except ValueError:
            pass

    def close(self) -> None:
        self._request_states.clear()
        self._waiting.clear()
        self._running.clear()
        self._finished_req_ids.clear()

    def _make_sched_req_id(self, request: OmniDiffusionRequest) -> str:
        """
        Generate a unique request ID for the given request.
        If the request already has request IDs, use the first one as the base.

        NOTE: OmniDiffusionRequest already contain multiple prompts/outputs
        as a pre-batched request object.
        """
        if request.request_ids:
            base = request.request_ids[0]
        else:
            base = f"req_{uuid.uuid4().hex[:8]}"

        sched_req_id = base
        suffix = 1
        while sched_req_id in self._request_states:
            sched_req_id = f"{base}#{suffix}"
            suffix += 1
        return sched_req_id
